version: "3.5"

services:

  postgres:
    image: postgres:12.2
    volumes:
      - frankyHome-pgData:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: testtest
    ports:
      - 5432:5432

volumes:
  frankyHome-pgData:
