version: "3.5"

services:

  # api:
  #   build: ./api
  #   working_dir: "/frankyHome/api"
  #   ports:
  #     - 3001:3001
  #   # depends_on:
  #   #   - postgres

  postgres:
    image: postgres:12.2
    volumes:
      - frankyHome-pgData:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: testtest
    ports:
      - 5432:5432

volumes:
  frankyHome-pgData:
